language: python
jobs:
  include:
  - stage: lint
    name: Python 2.7 lint
    python: '2.7'
    script: python -m flake8
  - stage: lint
    name: Python 3.6 lint
    python: '3.8'
    script: python -m flake8
  - stage: test
    python: '2.7'
    name: Python 2.7 tests
    script: PYTHONPATH=. pytest tests
  - stage: test
    name: Python 3.6 tests
    python: '3.8'
    script: PYTHONPATH=. pytest tests
  - stage: build_wheel
    name: Build Wheel
    script: python setup.py bdist_wheel
    python: '3.8'
    deploy:
      provider: releases
      skip_cleanup: true
      api_key: "${GITHUB_TOKEN}"
      file_glob: true
      file:
      - dist/*.whl
notifications:
  slack:
    on_success: always
    on_failure: always
    rooms:
      secure: jFZHqGc08BZN3kSUlTMNl+EQHk/jCLRmtXV0ADd5hL8AcOFasGHGc2fY03f8xymj04iicYyGNw/HGyMG2a53angvmRPFiQg28Ya+i7pqg+IkE3MOMO5uE7KG3llaSVS7IszNOvjbNhn4eErlrMq8QUu5gY4ccJC4YRwyh+bvjvTBwFJ1+uDDvlOnRyYQtKLeIS54c+p9Ax76/WgLb2Gk70GcAJfJaYSdh9Pcon3GLMjVMoM+m/PnXdW9LEYkZPhfIbRt8/iRwi7uKdSufsdwNgQLploZmd/5dd6jbPZ4s07HYSIWgPNyCESaQnRErEoKKVslq0+8n/eUuoKWcQjLdt0GMXB+nlZtN1Qxv4tqKRMksE8P2QqGmsyhiRFdtNgsz0fr0fBD4qdQvTqkkhz3FHv1iOzFpRng+59MzA1WppFpVqWYlyP0F3hAnxbfHb6INUjBx1zXSFp2yFpTGQMl769NmWMKyhPj2HPAu27olR/RfQD5Golh/zj3X4tPNQOugw1ZBCr6DvIS971koTaCDm1d5nt8g+CWRBFlE0VPSKtKTwzc9ppEYZBZ1Ofl9PtxYbReyoCIVTA3BGFpWQzjFehWj9nGwX+wPEDlK+iKO/ibnwqtMl+1dL53QYQPGRGnX0FpWQgBnIhJzvguutmBEctFlReWQgJ6pqoHLMHa4/M=
stages:
- lint
- test
- name: build_wheel
  if: branch = master
