language: python
jobs:
  include:
  - stage: lint
    name: Python 2.7 lint
    python: '2.7'
    script: python -m flake8
  - stage: lint
    name: Python 3.6 lint
    python: '3.6'
    script: python -m flake8
  - stage: test
    python: '2.7'
    name: Python 2.7 tests
    script: PYTHONPATH=. pytest tests
  - stage: test
    name: Python 3.6 tests
    python: '3.6'
    script: PYTHONPATH=. pytest tests
  - stage: build_wheel
    name: Build Wheel
    script: python setup.py bdist_wheel
    python: '3.6'
    deploy:
      provider: releases
      skip_cleanup: true
      api_key: "${GITHUB_TOKEN}"
      file_glob: true
      file:
      - dist/*.whl
notifications:
  slack:
    on_success: always
    on_failure: always
    rooms:
      secure: ml8DcgfDWy57youAIDhuDLQku9U48CVfENfOPH4a11CcCr7v05VMSbTLP8ahoTwp4GJh60n6GPlJdYPEVRpDs3cPTkNcEIU506BGPXz7Ct/lIT8HQkSWqMzgikVs7hhxDsO07P1OCV4VRi9eg1j7qnOBu8QWgkQIJFXa1vb6gCt6l5/z9wUrW5YtqJI4DBAlvORRUw17By5hybhDJCmKsb9/Luu+Jp0D0DQBu7o18JPnRIADguoTDrE85M41Rv4UaAkRxXbcnpYM13ui3SHJNubIN2nnZFbLpjIPP2gHa71NM9qBHKOc0azjReg6LtnuHeiUTC3EXn/mafQ/eyaOAngceW7xwsU4M8DvL7rDTJqVUHVGF9Q0HRKeKW4zwPeWs/qFbx+hwyMjUXrsw8FqukfNsgZrbZSA5LLn8QIBavnnBOekql8yh/FSl9wINIAbykfBqyn5z1O2rXaLOW3pBWX+QvO5L+zQOoG6vu5kxVqd1R/fcqTRcdeQqTKO/xhkThYjX6DtVN9qIm9mU0hepEZ/GgJo50QMU3RE3es99NpvAe81PTsG2MCrfQVkreV/3OUl9sFne9mq08OXWTNo5jRHME6L9anHX5F7+Vm6WiUmdPNKAGjG7mTrueWAB/VCGBqWH9WR5TjXkyNtBSYY4IoOv7oc6kuVn2sbUEbf8Mw=
stages:
- lint
- test
- name: build_wheel
  if: branch = master
