name: C/C++ CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
       os: [ubuntu-latest, self-hosted]
     
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Check cmake version
      run: cmake --version
  
    - name: Build
      run: cd cmake-example && mkdir build && cd build && cmake .. && make
      
    - name: Run exe
      run: cd cmake-example/build && ls && ./Main
