
name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04]
        python: ["3.8", "3.9", "3.10"]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Test with pytest
      run: |
        PYTHONPATH=. pytest tests
        
    - name: Build package
      run: |
        python setup.py bdist_wheel
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3.0.0
      if: github.ref == 'refs/heads/master'
      with:
        name: python-package-${{ matrix.python }}-${{ matrix.os }} 
        path: dist/*.whl
        retention-days: 5
    
    - name: Notify on Slack
      uses: slackapi/slack-github-action@v1.18.0
      with:
        channel-id: github-ci
        slack-message: "GitHub build result ${{ matrix.node }} ${{ matrix.python }} : ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        
    
